services:
  - type: web
    name: web3d-connector
    runtime: docker
    plan: free
    envVars:
      - key: DNxnIAFAyrHlLrqXtomrGeLRCx1KZxl6dy48lj7ANgA=
        sync: false
      - key: ghp_lcTOZLR71oBl4c0Ro2Mm4xkRbIHIR22B5f7T
        sync: false
    healthCheckPath: /
